CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "City" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "DepartmentId" integer,
    "RegionId" integer,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_City" PRIMARY KEY ("Id")
);

CREATE TABLE "Country" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Abbreviation" character varying(10) NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Country" PRIMARY KEY ("Id")
);

CREATE TABLE "Customer" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "MarriedLastName" character varying(100),
    "Address" character varying(250) NOT NULL,
    "IdentificationValue" character varying(50) NOT NULL,
    "GenderId" integer NOT NULL,
    "ProspectId" integer,
    "CountryId" integer NOT NULL,
    "IdentificationTypeId" integer NOT NULL,
    "NeighborhoodId" integer,
    "CityId" integer,
    "DepartmentId" integer,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Customer" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customer_City_CityId" FOREIGN KEY ("CityId") REFERENCES "City" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Customer_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Department" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "CountryId" integer,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Department" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Department_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Email" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(250) NOT NULL,
    "EmailName" character varying(150) NOT NULL,
    "CustomerId" uuid NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Email" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Email_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Gender" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Gender" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "UserName" character varying(50) NOT NULL,
    "GenderId" integer NOT NULL,
    "PasswordHash" bytea NOT NULL,
    "PasswordSalt" bytea NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_User_Gender_GenderId" FOREIGN KEY ("GenderId") REFERENCES "Gender" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_User_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_User_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_User_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "IdentificationType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_IdentificationType" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IdentificationType_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_IdentificationType_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_IdentificationType_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Neighborhood" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "CityId" integer,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Neighborhood" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Neighborhood_City_CityId" FOREIGN KEY ("CityId") REFERENCES "City" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Neighborhood_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Neighborhood_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Neighborhood_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PhoneNumber" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(250) NOT NULL,
    "Number" character varying(15) NOT NULL,
    "CustomerId" uuid NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_PhoneNumber" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhoneNumber_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PhoneNumber_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PhoneNumber_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PhoneNumber_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reference" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "PhoneNumber" character varying(15) NOT NULL,
    "Relationship" character varying(50) NOT NULL,
    "CustomerId" uuid NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Reference" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reference_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customer" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reference_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reference_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reference_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Region" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Region" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Region_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Region_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Region_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Prospect" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "MarriedLastName" character varying(100),
    "Address" character varying(250) NOT NULL,
    "GenderId" integer NOT NULL,
    "CountryId" integer NOT NULL,
    "IdentificationTypeId" integer NOT NULL,
    "NeighborhoodId" integer,
    "IdentificationValue" character varying(50) NOT NULL,
    "PhoneNumber" character varying(15) NOT NULL,
    "PhoneNumberDesc" character varying(250) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "EmailDesc" character varying(250) NOT NULL,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedById" uuid,
    "CreationDate" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(100),
    "UpdatedById" uuid,
    "UpdateDate" timestamp with time zone,
    "DeletedBy" character varying(100),
    "DeletedById" uuid,
    "DeletedDate" timestamp with time zone,
    CONSTRAINT "PK_Prospect" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prospect_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Country" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prospect_Gender_GenderId" FOREIGN KEY ("GenderId") REFERENCES "Gender" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prospect_IdentificationType_IdentificationTypeId" FOREIGN KEY ("IdentificationTypeId") REFERENCES "IdentificationType" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prospect_Neighborhood_NeighborhoodId" FOREIGN KEY ("NeighborhoodId") REFERENCES "Neighborhood" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prospect_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prospect_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prospect_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_City_CreatedById" ON "City" ("CreatedById");

CREATE INDEX "IX_City_DeletedById" ON "City" ("DeletedById");

CREATE INDEX "IX_City_DepartmentId" ON "City" ("DepartmentId");

CREATE INDEX "IX_City_RegionId" ON "City" ("RegionId");

CREATE INDEX "IX_City_UpdatedById" ON "City" ("UpdatedById");

CREATE INDEX "IX_Country_CreatedById" ON "Country" ("CreatedById");

CREATE INDEX "IX_Country_DeletedById" ON "Country" ("DeletedById");

CREATE INDEX "IX_Country_UpdatedById" ON "Country" ("UpdatedById");

CREATE INDEX "IX_Customer_CityId" ON "Customer" ("CityId");

CREATE INDEX "IX_Customer_CountryId" ON "Customer" ("CountryId");

CREATE INDEX "IX_Customer_CreatedById" ON "Customer" ("CreatedById");

CREATE INDEX "IX_Customer_DeletedById" ON "Customer" ("DeletedById");

CREATE INDEX "IX_Customer_DepartmentId" ON "Customer" ("DepartmentId");

CREATE INDEX "IX_Customer_GenderId" ON "Customer" ("GenderId");

CREATE INDEX "IX_Customer_IdentificationTypeId" ON "Customer" ("IdentificationTypeId");

CREATE INDEX "IX_Customer_NeighborhoodId" ON "Customer" ("NeighborhoodId");

CREATE INDEX "IX_Customer_ProspectId" ON "Customer" ("ProspectId");

CREATE INDEX "IX_Customer_UpdatedById" ON "Customer" ("UpdatedById");

CREATE INDEX "IX_Department_CountryId" ON "Department" ("CountryId");

CREATE INDEX "IX_Department_CreatedById" ON "Department" ("CreatedById");

CREATE INDEX "IX_Department_DeletedById" ON "Department" ("DeletedById");

CREATE INDEX "IX_Department_UpdatedById" ON "Department" ("UpdatedById");

CREATE INDEX "IX_Email_CreatedById" ON "Email" ("CreatedById");

CREATE INDEX "IX_Email_CustomerId" ON "Email" ("CustomerId");

CREATE INDEX "IX_Email_DeletedById" ON "Email" ("DeletedById");

CREATE INDEX "IX_Email_UpdatedById" ON "Email" ("UpdatedById");

CREATE INDEX "IX_Gender_CreatedById" ON "Gender" ("CreatedById");

CREATE INDEX "IX_Gender_DeletedById" ON "Gender" ("DeletedById");

CREATE INDEX "IX_Gender_UpdatedById" ON "Gender" ("UpdatedById");

CREATE INDEX "IX_IdentificationType_CreatedById" ON "IdentificationType" ("CreatedById");

CREATE INDEX "IX_IdentificationType_DeletedById" ON "IdentificationType" ("DeletedById");

CREATE INDEX "IX_IdentificationType_UpdatedById" ON "IdentificationType" ("UpdatedById");

CREATE INDEX "IX_Neighborhood_CityId" ON "Neighborhood" ("CityId");

CREATE INDEX "IX_Neighborhood_CreatedById" ON "Neighborhood" ("CreatedById");

CREATE INDEX "IX_Neighborhood_DeletedById" ON "Neighborhood" ("DeletedById");

CREATE INDEX "IX_Neighborhood_UpdatedById" ON "Neighborhood" ("UpdatedById");

CREATE INDEX "IX_PhoneNumber_CreatedById" ON "PhoneNumber" ("CreatedById");

CREATE INDEX "IX_PhoneNumber_CustomerId" ON "PhoneNumber" ("CustomerId");

CREATE INDEX "IX_PhoneNumber_DeletedById" ON "PhoneNumber" ("DeletedById");

CREATE INDEX "IX_PhoneNumber_UpdatedById" ON "PhoneNumber" ("UpdatedById");

CREATE INDEX "IX_Prospect_CountryId" ON "Prospect" ("CountryId");

CREATE INDEX "IX_Prospect_CreatedById" ON "Prospect" ("CreatedById");

CREATE INDEX "IX_Prospect_DeletedById" ON "Prospect" ("DeletedById");

CREATE INDEX "IX_Prospect_GenderId" ON "Prospect" ("GenderId");

CREATE INDEX "IX_Prospect_IdentificationTypeId" ON "Prospect" ("IdentificationTypeId");

CREATE INDEX "IX_Prospect_NeighborhoodId" ON "Prospect" ("NeighborhoodId");

CREATE INDEX "IX_Prospect_UpdatedById" ON "Prospect" ("UpdatedById");

CREATE INDEX "IX_Reference_CreatedById" ON "Reference" ("CreatedById");

CREATE INDEX "IX_Reference_CustomerId" ON "Reference" ("CustomerId");

CREATE INDEX "IX_Reference_DeletedById" ON "Reference" ("DeletedById");

CREATE INDEX "IX_Reference_UpdatedById" ON "Reference" ("UpdatedById");

CREATE INDEX "IX_Region_CreatedById" ON "Region" ("CreatedById");

CREATE INDEX "IX_Region_DeletedById" ON "Region" ("DeletedById");

CREATE INDEX "IX_Region_UpdatedById" ON "Region" ("UpdatedById");

CREATE INDEX "IX_User_CreatedById" ON "User" ("CreatedById");

CREATE INDEX "IX_User_DeletedById" ON "User" ("DeletedById");

CREATE INDEX "IX_User_GenderId" ON "User" ("GenderId");

CREATE INDEX "IX_User_UpdatedById" ON "User" ("UpdatedById");

ALTER TABLE "City" ADD CONSTRAINT "FK_City_Department_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Department" ("Id") ON DELETE CASCADE;

ALTER TABLE "City" ADD CONSTRAINT "FK_City_Region_RegionId" FOREIGN KEY ("RegionId") REFERENCES "Region" ("Id") ON DELETE RESTRICT;

ALTER TABLE "City" ADD CONSTRAINT "FK_City_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "City" ADD CONSTRAINT "FK_City_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "City" ADD CONSTRAINT "FK_City_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Country" ADD CONSTRAINT "FK_Country_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Country" ADD CONSTRAINT "FK_Country_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Country" ADD CONSTRAINT "FK_Country_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_Department_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Department" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_Gender_GenderId" FOREIGN KEY ("GenderId") REFERENCES "Gender" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_IdentificationType_IdentificationTypeId" FOREIGN KEY ("IdentificationTypeId") REFERENCES "IdentificationType" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_Neighborhood_NeighborhoodId" FOREIGN KEY ("NeighborhoodId") REFERENCES "Neighborhood" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_Prospect_ProspectId" FOREIGN KEY ("ProspectId") REFERENCES "Prospect" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Customer" ADD CONSTRAINT "FK_Customer_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Department" ADD CONSTRAINT "FK_Department_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Department" ADD CONSTRAINT "FK_Department_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Department" ADD CONSTRAINT "FK_Department_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Email" ADD CONSTRAINT "FK_Email_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Email" ADD CONSTRAINT "FK_Email_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Email" ADD CONSTRAINT "FK_Email_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Gender" ADD CONSTRAINT "FK_Gender_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Gender" ADD CONSTRAINT "FK_Gender_User_DeletedById" FOREIGN KEY ("DeletedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Gender" ADD CONSTRAINT "FK_Gender_User_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "User" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250807062828_InitialCreate', '9.0.8');

COMMIT;

